### ISSUE TITLE
Error when ip in service is null

### ISSUE THREAD

**Issue by ghost** [homenoc/dsbd-web-admin#120]
ref. https://github.com/homenoc/dsbd-web-admin/blob/develop/src/pages/Add/ConnectionAdd.tsx#L248

I am a HomeNOC user.
When I try to add my connection information, I get the following error and cannot proceed with the application.
From what I can see, it is Forced Unwrapping, so if the ip is null, an exception will be thrown.
Therefore, I think it would be better to make the error occur when the ip is null.

| trace | service |
| --- | --- |
| <img width="621" src="https://user-images.githubusercontent.com/15951796/185404112-8d4bd508-5cdc-44dc-b4da-8a3300c75a8d.png"> | <img width="515"  src="https://user-images.githubusercontent.com/15951796/185404119-6f7b5037-1cff-40f3-8065-929363b94a8d.png"> |

```
ConnectionAdd.tsx:290 Uncaught TypeError: Cannot read properties of null (reading 'filter')
    at hA (ConnectionAdd.tsx:290:118)
    at la (react-dom.production.min.js:157:137)
    at Va (react-dom.production.min.js:180:154)
    at $l (react-dom.production.min.js:269:343)
    at Ts (react-dom.production.min.js:250:347)
    at Zs (react-dom.production.min.js:250:278)
    at Es (react-dom.production.min.js:250:138)
    at bs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

**Comment by symysak** [comment]
Let me know the service id?
I'll check it.
